sudo: required
dist: trusty
language: cpp

notifications:
    email: false

compiler:
    - g++-4.8
python:
    - "3.5"
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - export python="/usr/bin/python"
addons:
    apt:
        sources:
        - kalakris-cmake
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
        - cmake
        - bison
        - python-virtualenv
        - python-pip

before_script:
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90 

script: 
    - git fetch origin master:refs/remotes/origin/master
    - make travis
    - make diff-cover
