name: CI
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches:
      - '**'
jobs:
  test:
    name: Tests
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        cxx: [clang++, g++]
        test-set:
          - test-native-regular
          - test-native-fulldebug
          - test-native-opt
          - test-examples
          # - test-cookiecutter
    env:
      CXX: ${{ matrix.cxx }}
      TEST_SET: ${{ matrix.test-set }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -qq g++-8 cmake build-essential python-pip python-virtualenv nodejs tar gzip libpthread-stubs0-dev libc6-dbg gdb
      - run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
      - run: git fetch origin master:refs/remotes/origin/master
      - run: make install-test-dependencies
      - run: ${CXX} --version
      - run: |
          source third-party/emsdk/emsdk_env.sh
          make ${TEST_SET} CXX=${CXX}
  test-web:
    name: Web Tests
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
    steps:
      - run: sudo apt-get install -qq g++-8 cmake build-essential python-pip python-virtualenv nodejs tar gzip libpthread-stubs0-dev libc6-dbg gdb
      - run: make install-test-dependencies
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: make test-web
