name: CI
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches:
      - '**'
jobs:
  test:
    name: Tests
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        cxx: [clang++, g++]
        test-set:
          - test-web
          - test-native-regular
          - test-native-fulldebug
          - test-native-opt
          - test-examples
          - test-cookiecutter
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.5'
      - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -qq g++-8 cmake build-essential python-virtualenv python-pip nodejs tar gzip libpthread-stubs0-dev libc6-dbg gdb
      - run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
      - run: git fetch origin master:refs/remotes/origin/master
      - run: npm install source-map
      - run: export python="/usr/bin/python" && make install-test-dependencies
      - run: source third-party/emsdk/emsdk_env.sh
      - run: ${CXX} --version
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: make ${TEST_SET} CXX=${CXX}
